version: "3.3"
services:
  database:
    build:
      context: ../database
      args:
        UFDL_POSTGRESQL_USER: ${UFDL_POSTGRESQL_USER}
        UFDL_POSTGRESQL_PASSWORD: ${UFDL_POSTGRESQL_PASSWORD}
    expose:
      - "5432/tcp"
    image: public.aml-repo.cms.waikato.ac.nz:443/ufdl/ufdl_postgres:latest
    volumes:
      - pg:/var/lib/postgresql/15/main

  redis:
    expose:
      - "6379/tcp"
    image: public.aml-repo.cms.waikato.ac.nz:443/redis:latest

  ufdl:
    build:
      args:
        UFDL_FRONTEND_BRANCH: ${UFDL_FRONTEND_BRANCH:-main}
      context: ../..
      dockerfile: docker/backend/Dockerfile
    depends_on:
      - database
      - redis
    environment:
      UFDL_DATABASE_TYPE: postgresql
      UFDL_POSTGRESQL_USER: ${UFDL_POSTGRESQL_USER}
      UFDL_POSTGRESQL_PASSWORD: ${UFDL_POSTGRESQL_PASSWORD}
      UFDL_POSTGRESQL_HOST: database
      UFDL_REDIS_HOST: redis
      UFDL_RESET_BACKEND_ON_RUN: ${UFDL_RESET_BACKEND_ON_RUN}
      UFDL_SERVER_PORT: ${UFDL_SERVER_PORT:-8000}
    image: public.aml-repo.cms.waikato.ac.nz:443/ufdl/ufdl_backend:latest
    ports:
      - target: 8000
        published: ${UFDL_SERVER_PORT:-8000}
        protocol: tcp
        mode: host
    volumes:
      - fs:/ufdl/ufdl-backend/fs
      - ./extra/:/ufdl/static/extra

  job-launcher:
    depends_on:
      - ufdl
    image: public.aml-repo.cms.waikato.ac.nz:443/ufdl/ufdl_job_launcher:latest
    profiles:
      - with-job-launcher
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/ufdl-job-launcher:/tmp/ufdl-job-launcher
      - ./job-launcher-docker.conf:/ufdl/ufdl-job-launcher/examples/job-launcher-example.conf

  job-launcher-gpu:
    depends_on:
      - ufdl
    image: public.aml-repo.cms.waikato.ac.nz:443/ufdl/ufdl_job_launcher-gpu:latest
    profiles:
      - with-job-launcher-gpu
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/ufdl-job-launcher:/tmp/ufdl-job-launcher
      - ./job-launcher-docker.conf:/ufdl/ufdl-job-launcher/examples/job-launcher-example.conf
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]

volumes:
  pg:
  fs:

