# Generated by Django 2.2.16 on 2020-10-02 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ufdl-core', '0002_the_rest'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectDetectionDataset',
            fields=[
                ('dataset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ufdl-core.Dataset')),
            ],
            options={
                'abstract': False,
            },
            bases=('ufdl-core.dataset',),
        ),
        migrations.CreateModel(
            name='Annotations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(editable=False, max_length=200)),
                ('annotations', models.TextField()),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='annotations', to='ufdl-object-detection.ObjectDetectionDataset')),
            ],
        ),
        migrations.AddConstraint(
            model_name='annotations',
            constraint=models.UniqueConstraint(fields=('dataset', 'filename'), name='unique_annotations_per_image'),
        ),
    ]
