# Generated by Django 2.2.6 on 2020-03-04 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ufdl-core', '0002_the_rest'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectDetectionDataset',
            fields=[
                ('dataset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ufdl-core.Dataset')),
            ],
            options={
                'abstract': False,
            },
            bases=('ufdl-core.dataset',),
        ),
    ]
