# Generated by Django 2.2.19 on 2022-04-19 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ufdl_core', '0002_the_rest'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetToLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DatasetToPrefix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ObjectDetectionDataset',
            fields=[
                ('dataset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ufdl_core.Dataset')),
            ],
            options={
                'abstract': False,
            },
            bases=('ufdl_core.dataset',),
        ),
        migrations.CreateModel(
            name='Prefix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(unique=True)),
                ('datasets', models.ManyToManyField(related_name='prefixes', through='ufdl_object_detection.DatasetToPrefix', to='ufdl_object_detection.ObjectDetectionDataset')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(unique=True)),
                ('datasets', models.ManyToManyField(related_name='labels', through='ufdl_object_detection.DatasetToLabel', to='ufdl_object_detection.ObjectDetectionDataset')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='datasettoprefix',
            name='dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ufdl_object_detection.ObjectDetectionDataset'),
        ),
        migrations.AddField(
            model_name='datasettoprefix',
            name='prefix',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ufdl_object_detection.Prefix'),
        ),
        migrations.AddField(
            model_name='datasettolabel',
            name='dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ufdl_object_detection.ObjectDetectionDataset'),
        ),
        migrations.AddField(
            model_name='datasettolabel',
            name='label',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ufdl_object_detection.Label'),
        ),
        migrations.CreateModel(
            name='Annotations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(default=None, max_length=4, null=True)),
                ('width', models.IntegerField(default=None, null=True)),
                ('height', models.IntegerField(default=None, null=True)),
                ('video_length', models.FloatField(default=None, null=True)),
                ('file', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ufdl_core.FileReference')),
            ],
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('time', models.FloatField(default=None, null=True)),
                ('polygon', models.TextField(default=None, null=True)),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='annotations', to='ufdl_object_detection.Annotations')),
                ('label_reference', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='annotations', to='ufdl_object_detection.DatasetToLabel')),
                ('prefix_reference', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='annotations', to='ufdl_object_detection.DatasetToPrefix')),
            ],
        ),
    ]
