# Generated by Django 2.2.13 on 2020-12-03 19:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import ufdl.core_app.models._User


class Migration(migrations.Migration):

    dependencies = [
        ('simple_django_teams', '0003_add_execute_permission'),
        ('ufdl_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CUDAVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.DecimalField(decimal_places=1, max_digits=4, unique=True)),
                ('full_version', models.CharField(max_length=16, unique=True)),
                ('min_driver_version', models.CharField(max_length=16)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DataDomain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2, unique=True)),
                ('description', models.CharField(max_length=32)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('deletion_time', models.DateTimeField(default=None, editable=False, null=True)),
                ('is_public', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=200)),
                ('version', models.IntegerField(default=1, editable=False)),
                ('previous_version', models.IntegerField(default=-1, editable=False)),
                ('description', models.TextField(blank=True)),
                ('tags', models.TextField()),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
                'default_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='DockerImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('version', models.CharField(max_length=32)),
                ('url', models.CharField(max_length=200)),
                ('registry_url', models.CharField(max_length=200)),
                ('registry_username', models.CharField(max_length=64, null=True)),
                ('registry_password', models.CharField(max_length=64, null=True)),
                ('cpu', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DockerImageToJobContract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle', models.CharField(max_length=128)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
                'default_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='Filename',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(editable=False, max_length=200)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
                'default_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='FileReference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metadata', models.TextField(blank=True, default='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Framework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('version', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Hardware',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generation', models.CharField(max_length=32)),
                ('min_compute_capability', models.FloatField()),
                ('max_compute_capability', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('deletion_time', models.DateTimeField(default=None, editable=False, null=True)),
                ('start_time', models.DateTimeField(default=None, editable=False, null=True)),
                ('end_time', models.DateTimeField(default=None, editable=False, null=True)),
                ('error_reason', models.TextField(default=None, null=True)),
                ('input_values', models.TextField()),
                ('parameter_values', models.TextField(null=True)),
                ('description', models.TextField(blank=True)),
                ('progress_amount', models.FloatField(default=0.0)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
                'default_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='JobContract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('pkg', models.CharField(max_length=64)),
                ('cls', models.CharField(max_length=256, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JobOutput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('deletion_time', models.DateTimeField(default=None, editable=False, null=True)),
                ('name', models.CharField(max_length=200)),
                ('type', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='JobTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('deletion_time', models.DateTimeField(default=None, editable=False, null=True)),
                ('name', models.CharField(max_length=200)),
                ('version', models.IntegerField(default=1)),
                ('description', models.TextField(blank=True)),
                ('scope', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='JobType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('pkg', models.CharField(max_length=64)),
                ('cls', models.CharField(max_length=256, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Licence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Limitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('level', models.PositiveSmallIntegerField()),
                ('is_internal', models.BooleanField(default=False, editable=False)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MetaTemplateChildRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MetaTemplateDependency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('deletion_time', models.DateTimeField(default=None, editable=False, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NamedFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canonical_source', models.CharField(default=None, max_length=256, null=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
                'default_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=39)),
                ('index', models.PositiveSmallIntegerField()),
                ('driver_version', models.CharField(max_length=16, null=True)),
                ('gpu_mem', models.BigIntegerField(null=True)),
                ('cpu_mem', models.BigIntegerField()),
                ('last_seen', models.DateTimeField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NotificationAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transition_index', models.PositiveSmallIntegerField(choices=[(0, 'ACQUIRE'), (1, 'RELEASE'), (2, 'START'), (3, 'PROGRESS'), (4, 'FINISH'), (5, 'ERROR'), (6, 'RESET'), (7, 'ABORT'), (8, 'CANCEL')])),
                ('suppress', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='NotificationOverride',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('override', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('types', models.TextField()),
                ('default', models.TextField(null=True)),
                ('default_type', models.TextField()),
                ('const', models.BooleanField()),
                ('help', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', ufdl.core_app.models._User.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='EmailNotification',
            fields=[
                ('notification_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ufdl_core.Notification')),
                ('subject', models.TextField()),
                ('body', models.TextField()),
                ('to', models.TextField(null=True)),
                ('cc', models.TextField(null=True)),
                ('bcc', models.TextField(null=True)),
            ],
            bases=('ufdl_core.notification',),
        ),
        migrations.CreateModel(
            name='MetaTemplate',
            fields=[
                ('jobtemplate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ufdl_core.JobTemplate')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
                'default_manager_name': 'objects',
            },
            bases=('ufdl_core.jobtemplate',),
        ),
        migrations.CreateModel(
            name='PreTrainedModel',
            fields=[
                ('model_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ufdl_core.Model')),
                ('url', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('name', models.CharField(max_length=200)),
                ('metadata', models.TextField(blank=True, default='')),
            ],
            options={
                'abstract': False,
            },
            bases=('ufdl_core.model',),
        ),
        migrations.CreateModel(
            name='PrintNotification',
            fields=[
                ('notification_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ufdl_core.Notification')),
                ('message', models.TextField()),
            ],
            bases=('ufdl_core.notification',),
        ),
        migrations.CreateModel(
            name='WebSocketNotification',
            fields=[
                ('notification_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ufdl_core.Notification')),
            ],
            bases=('ufdl_core.notification',),
        ),
        migrations.CreateModel(
            name='WorkableTemplate',
            fields=[
                ('jobtemplate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ufdl_core.JobTemplate')),
                ('type', models.CharField(max_length=256)),
                ('executor_class', models.CharField(default='', max_length=128)),
                ('required_packages', models.TextField(blank=True, default='')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
                'default_manager_name': 'objects',
            },
            bases=('ufdl_core.jobtemplate',),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('deletion_time', models.DateTimeField(default=None, editable=False, null=True)),
                ('name', models.CharField(max_length=200)),
                ('creator', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='projects', to='simple_django_teams.Team')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
                'default_manager_name': 'objects',
            },
        ),
        migrations.AddConstraint(
            model_name='permission',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_permission_names'),
        ),
        migrations.AddField(
            model_name='parameter',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='parameters', to='ufdl_core.JobTemplate'),
        ),
        migrations.AddField(
            model_name='notificationoverride',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='notification_overrides', to='ufdl_core.Job'),
        ),
        migrations.AddField(
            model_name='notificationaction',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='notification_actions', to='ufdl_core.Job'),
        ),
        migrations.AddField(
            model_name='notificationaction',
            name='notification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ufdl_core.Notification'),
        ),
        migrations.AddField(
            model_name='node',
            name='current_job',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ufdl_core.Job'),
        ),
        migrations.AddField(
            model_name='node',
            name='hardware_generation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='nodes', to='ufdl_core.Hardware'),
        ),
        migrations.AddField(
            model_name='namedfile',
            name='file',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ufdl_core.File'),
        ),
        migrations.AddField(
            model_name='namedfile',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ufdl_core.Filename'),
        ),
        migrations.AddField(
            model_name='model',
            name='creator',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='model',
            name='data',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ufdl_core.NamedFile'),
        ),
        migrations.AddField(
            model_name='model',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='models', to='ufdl_core.DataDomain'),
        ),
        migrations.AddField(
            model_name='model',
            name='framework',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='models', to='ufdl_core.Framework'),
        ),
        migrations.AddField(
            model_name='model',
            name='licence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='models', to='ufdl_core.Licence'),
        ),
        migrations.AddField(
            model_name='metatemplatedependency',
            name='dependency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='dependents', to='ufdl_core.MetaTemplateChildRelation'),
        ),
        migrations.AddField(
            model_name='metatemplatedependency',
            name='dependent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='dependencies', to='ufdl_core.MetaTemplateChildRelation'),
        ),
        migrations.AddField(
            model_name='metatemplatedependency',
            name='input',
            field=models.TextField(),
        ),
        migrations.AddField(
            model_name='metatemplatechildrelation',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ufdl_core.JobTemplate'),
        ),
        migrations.AddConstraint(
            model_name='limitation',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_limitation_names'),
        ),
        migrations.AddField(
            model_name='licence',
            name='conditions',
            field=models.ManyToManyField(related_name='+', to='ufdl_core.Condition'),
        ),
        migrations.AddField(
            model_name='licence',
            name='domains',
            field=models.ManyToManyField(related_name='+', to='ufdl_core.Domain'),
        ),
        migrations.AddField(
            model_name='licence',
            name='limitations',
            field=models.ManyToManyField(related_name='+', to='ufdl_core.Limitation'),
        ),
        migrations.AddField(
            model_name='licence',
            name='permissions',
            field=models.ManyToManyField(related_name='+', to='ufdl_core.Permission'),
        ),
        migrations.AddField(
            model_name='jobtemplate',
            name='creator',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobtemplate',
            name='domain',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='job_templates', to='ufdl_core.DataDomain'),
        ),
        migrations.AddField(
            model_name='jobtemplate',
            name='licence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='job_templates', to='ufdl_core.Licence'),
        ),
        migrations.AddField(
            model_name='joboutput',
            name='creator',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='joboutput',
            name='data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ufdl_core.File'),
        ),
        migrations.AddField(
            model_name='joboutput',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='outputs', to='ufdl_core.Job'),
        ),
        migrations.AddField(
            model_name='job',
            name='creator',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='job',
            name='node',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='jobs', to='ufdl_core.Node'),
        ),
        migrations.AddField(
            model_name='job',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='children', to='ufdl_core.Job'),
        ),
        migrations.AddField(
            model_name='job',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='jobs', to='ufdl_core.JobTemplate'),
        ),
        migrations.AddConstraint(
            model_name='hardware',
            constraint=models.UniqueConstraint(fields=('generation',), name='unique_generation_names'),
        ),
        migrations.AddConstraint(
            model_name='framework',
            constraint=models.UniqueConstraint(fields=('name', 'version'), name='unique_frameworks'),
        ),
        migrations.AddField(
            model_name='filereference',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='file_references', to='ufdl_core.NamedFile'),
        ),
        migrations.AddConstraint(
            model_name='filename',
            constraint=models.UniqueConstraint(fields=('filename',), name='unique_filenames'),
        ),
        migrations.AddConstraint(
            model_name='file',
            constraint=models.UniqueConstraint(fields=('handle',), name='unique_file_handles'),
        ),
        migrations.AddConstraint(
            model_name='domain',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_domain_names'),
        ),
        migrations.AddField(
            model_name='dockerimagetojobcontract',
            name='docker_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ufdl_core.DockerImage'),
        ),
        migrations.AddField(
            model_name='dockerimagetojobcontract',
            name='job_contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ufdl_core.JobContract'),
        ),
        migrations.AddField(
            model_name='dockerimage',
            name='cuda_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='docker_images', to='ufdl_core.CUDAVersion'),
        ),
        migrations.AddField(
            model_name='dockerimage',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='docker_images', to='ufdl_core.DataDomain'),
        ),
        migrations.AddField(
            model_name='dockerimage',
            name='framework',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='docker_images', to='ufdl_core.Framework'),
        ),
        migrations.AddField(
            model_name='dockerimage',
            name='licence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='docker_images', to='ufdl_core.Licence'),
        ),
        migrations.AddField(
            model_name='dockerimage',
            name='min_hardware_generation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ufdl_core.Hardware'),
        ),
        migrations.AddField(
            model_name='dockerimage',
            name='tasks',
            field=models.ManyToManyField(related_name='docker_images', through='ufdl_core.DockerImageToJobContract', to='ufdl_core.JobContract'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='creator',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dataset',
            name='domain',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='datasets', to='ufdl_core.DataDomain'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='files',
            field=models.ManyToManyField(related_name='+', to='ufdl_core.FileReference'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='licence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='datasets', to='ufdl_core.Licence'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='datasets', to='ufdl_core.Project'),
        ),
        migrations.AddConstraint(
            model_name='condition',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_condition_names'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(condition=models.Q(deletion_time__isnull=True), fields=('name', 'team'), name='unique_active_project_names_per_team'),
        ),
        migrations.AddConstraint(
            model_name='printnotification',
            constraint=models.UniqueConstraint(fields=('message',), name='unique_print_notifications'),
        ),
        migrations.AddConstraint(
            model_name='parameter',
            constraint=models.UniqueConstraint(fields=('template', 'name'), name='unique_template_parameter_names'),
        ),
        migrations.AddConstraint(
            model_name='notificationoverride',
            constraint=models.UniqueConstraint(fields=('job', 'name'), name='unique_child_notification_overrides'),
        ),
        migrations.AddConstraint(
            model_name='notificationaction',
            constraint=models.UniqueConstraint(fields=('job', 'transition_index', 'notification'), name='unique_notifications'),
        ),
        migrations.AddConstraint(
            model_name='node',
            constraint=models.UniqueConstraint(fields=('ip', 'index'), name='unique_nodes'),
        ),
        migrations.AddConstraint(
            model_name='namedfile',
            constraint=models.UniqueConstraint(condition=models.Q(canonical_source__isnull=True), fields=('name', 'file'), name='unique_filename_file_pairs'),
        ),
        migrations.AddConstraint(
            model_name='namedfile',
            constraint=models.UniqueConstraint(condition=models.Q(canonical_source__isnull=False), fields=('name', 'canonical_source'), name='unique_filename_file_pairs_2'),
        ),
        migrations.AddConstraint(
            model_name='metatemplatedependency',
            constraint=models.UniqueConstraint(fields=('dependency', 'output', 'dependent', 'input'), name='unique_meta_template_dependencies'),
        ),
        migrations.AddField(
            model_name='metatemplatechildrelation',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='child_relations', to='ufdl_core.MetaTemplate'),
        ),
        migrations.AddConstraint(
            model_name='licence',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_licence_names'),
        ),
        migrations.AddConstraint(
            model_name='jobtemplate',
            constraint=models.UniqueConstraint(condition=models.Q(deletion_time__isnull=True), fields=('name', 'version'), name='unique_active_job_templates'),
        ),
        migrations.AddConstraint(
            model_name='joboutput',
            constraint=models.UniqueConstraint(fields=('job', 'name', 'type'), name='unique_job_outputs'),
        ),
        migrations.AddConstraint(
            model_name='emailnotification',
            constraint=models.UniqueConstraint(fields=('subject', 'body', 'to', 'cc', 'bcc'), name='unique_email_notifications'),
        ),
        migrations.AddConstraint(
            model_name='dockerimage',
            constraint=models.UniqueConstraint(fields=('name', 'version'), name='unique_docker_images'),
        ),
        migrations.AddConstraint(
            model_name='dataset',
            constraint=models.UniqueConstraint(condition=models.Q(deletion_time__isnull=True), fields=('name', 'version', 'project'), name='unique_active_datasets_per_project'),
        ),
        migrations.AddConstraint(
            model_name='metatemplatechildrelation',
            constraint=models.UniqueConstraint(fields=('parent', 'name'), name='unique_meta_template_children'),
        ),
    ]
