# Generated by Django 4.1.3 on 2022-12-11 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ufdl_core', '0007_job_contracts'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpectrumClassificationDataset',
            fields=[
                ('dataset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ufdl_core.dataset')),
            ],
            options={
                'abstract': False,
            },
            bases=('ufdl_core.dataset',),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.TextField()),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sc_categories', to='ufdl_core.filereference')),
            ],
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('file', 'category'), name='unique_categories_for_spectra'),
        ),
    ]
