# Generated by Django 2.2.6 on 2020-06-17 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ufdl_core', '0002_the_rest'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeechDataset',
            fields=[
                ('dataset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ufdl_core.Dataset')),
                ('transcriptions', models.TextField()),
            ],
            options={
                'abstract': False,
            },
            bases=('ufdl_core.dataset',),
        ),
    ]
